/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package employee.payroll;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;


/**
 *
 * @author dsajw
 */
public class addEmployee extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;


    /** Creates new form addEmployee */
    public addEmployee(){
        initComponents();
         conn=db.getConnection();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
         idcount();
        lbl_emp.setText(Emp.username);
        
     
      }
   
    public int idcount()
    { 
    
      try
      {
      Statement st=null; 
      String sql="Select * from Staff_information";
      st=conn.createStatement();
      rs=st.executeQuery(sql);
      rs.next();
      txt_id.setText("1");
      c=rs.getInt("id");
      
      while(rs.next())
      {
              
              l=rs.getInt("id");
              if(c>l)
              
                  txt_id.setText(String.valueOf(c+1));
              
              else
              {
                 txt_id.setText(String.valueOf(l+1));
                 c=l;
              }
      }
      }
      catch(Exception e)
      {
        e.printStackTrace();
      }
        
      return c;
    }
    public void clear()
    {
        if(!jLabel19.isVisible())
        txt_id.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_contact.setText("");
        txt_dob.setDate(null);
        txt_email.setText("");
        txt_email.setText("");
        txt_dept.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_address1.setText("");
        txt_address2.setText("");
        txt_pc.setText("");
        img.setIcon(null);
        txt_desig.setText("");
        txt_job.setText("");
        txt_apt.setText("");
        txt_doj.setDate(null);
        r_male.setSelected(false);
        r_female.setSelected(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_firstname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_address2 = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        txt_apt = new javax.swing.JTextField();
        txt_desig = new javax.swing.JTextField();
        txt_dept = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_address1 = new javax.swing.JTextField();
        lbl_back = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_dob = new org.jdesktop.swingx.JXDatePicker();
        txt_doj = new org.jdesktop.swingx.JXDatePicker();
        label = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(901, 660));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_firstname.setInputVerifier(new firstname());
        txt_firstname.setMinimumSize(new java.awt.Dimension(5, 20));
        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 137, 29));

        txt_id.setInputVerifier(new numbers());
        txt_id.setMinimumSize(new java.awt.Dimension(5, 20));
        txt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idFocusLost(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 137, 29));

        txt_surname.setInputVerifier(new firstname());
        txt_surname.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 137, 29));

        txt_contact.setInputVerifier(new numbers());
        txt_contact.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 137, 29));

        txt_email.setInputVerifier(new emailid());
        txt_email.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 137, 29));

        txt_address2.setInputVerifier(new Sentence());
        txt_address2.setMinimumSize(new java.awt.Dimension(5, 20));
        txt_address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_address2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 137, 29));

        txt_pc.setInputVerifier(new numbers());
        txt_pc.setMinimumSize(new java.awt.Dimension(5, 20));
        txt_pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pcActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 137, 29));

        txt_apt.setInputVerifier(new numbers());
        txt_apt.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_apt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 137, 29));

        txt_desig.setInputVerifier(new Sentence());
        txt_desig.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_desig, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 137, 29));

        txt_dept.setInputVerifier(new Sentence());
        txt_dept.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 137, 29));

        txt_salary.setInputVerifier(new numbers());
        txt_salary.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 137, 29));

        txt_job.setInputVerifier(new Sentence());
        txt_job.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 137, 29));

        txt_status.setInputVerifier(new Sentence());
        txt_status.setMinimumSize(new java.awt.Dimension(5, 20));
        txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusActionPerformed(evt);
            }
        });
        getContentPane().add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 137, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Employee ID:");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date Of Birth:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Surname:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("First Name:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Address2:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address1:");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contact:");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 80, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Apt./House No:");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Designation:");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Department:");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Post Code:");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Date Hired:");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Status:");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Job Title:");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Basic Salary:");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Save-icon.png"))); // NOI18N
        jButton1.setText("Add Record");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Gender:");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        r_male.setText("Male");
        r_male.setInputVerifier(new gender());
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        getContentPane().add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 60, -1));

        r_female.setText("Female");
        r_female.setInputVerifier(new gender());
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/erase-128.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 120, 30));

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 34, 140, 150));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/attach.png"))); // NOI18N
        jButton3.setText("Update Photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        txt_search.setInputVerifier(new searchv());
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 330, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/delete_16x16.gif"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 120, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/update icon.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Search Employee By ID:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 310, 30));

        txt_address1.setInputVerifier(new Sentence());
        txt_address1.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(txt_address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 137, 29));

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Right3Green.png"))); // NOI18N
        lbl_back.setText("Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 50, 40));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Logged in As :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        txt_emp.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp.setText("Employee ID");
        getContentPane().add(txt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, -1, -1));

        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setText("Auto Generated");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 194, 90, 20));

        txt_dob.setFormats("dd/MM/yyyy");
        txt_dob.setInputVerifier(new dob());
        getContentPane().add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 140, 30));

        txt_doj.setFormats("dd/MM/yyyy");
        txt_doj.setInputVerifier(new dob());
        getContentPane().add(txt_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 140, 30));

        label.setText("Logged in as:");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 80, -1));

        lbl_emp.setText("emp");
        getContentPane().add(lbl_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 140, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/frame.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_address2ActionPerformed

    private void txt_pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pcActionPerformed

    private void txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int x=JOptionPane.showConfirmDialog(this,"Are you sure to add record?","Add Record",JOptionPane.YES_NO_OPTION);
     if(x==0)
     {
        try {
                String sql ="insert into Staff_information " 
                        + "(first_name,surname,Dob,Email,"
                        + "Telephone,Address,Department,"
                        + "id,Salary,Gender,Address2,"
                        + "Post_code, Designation,Status,job_title,Apartment,Date_hired,image) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
         
             
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_firstname.getText());
                pst.setString(2,txt_surname.getText());
                java.util.Date dob=new java.util.Date();
                dob=txt_dob.getDate();
                java.util.Date doj=new java.util.Date();
                doj=txt_doj.getDate();
                java.sql.Date dob1=new java.sql.Date(dob.getTime());
                java.sql.Date doj1=new java.sql.Date(doj.getTime());
                DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
                String dob2=df.format(dob1);
                String doj2=df.format(doj1);
                pst.setString(3,dob2);
                pst.setString(4,txt_email.getText());
                pst.setString(5,txt_contact.getText());
                pst.setString(6,txt_address1.getText());
                pst.setString(7,txt_dept.getText());
                pst.setInt(8,Integer.parseInt(txt_id.getText()));
                pst.setString(9,txt_salary.getText());
                if(r_male.isSelected())
                    gender="m";
                else if(r_female.isSelected())
                    gender="f";
                pst.setString(10, gender);
                pst.setString(11,txt_address2.getText());
                pst.setString(12,txt_pc.getText());
                pst.setString(13,txt_desig.getText());
                pst.setString(14,txt_status.getText());
                pst.setString(15,txt_job.getText());
                pst.setString(16,txt_apt.getText());
                pst.setString(17,doj2);
                pst.setBytes(18, person_image);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data is saved successfully");
                
                clear();
            
           
        }
       /*  catch(SQLIntegrityConstraintViolationException e1)
        {
             int j=JOptionPane.showConfirmDialog(null,"The id you have entered is already existing.Click YES to get one","ID exists",JOptionPane.YES_NO_OPTION);
               if(j==0)
               {
                 idcount();
               }
        }*/
         catch(NullPointerException e)
        {
         JOptionPane.showMessageDialog(this,"One or more fields may be empty");
        }
        catch(SQLException se){
            se.printStackTrace();

        }
        
        catch (Exception e)

            {
                 e.printStackTrace();
            }
            try
            {Statement st=null;
              String sq="select * from Staff_information where (id) NOT IN (select id from users)";
              st=conn.createStatement();
              rs=st.executeQuery(sq);
              while(rs.next())
              {
                String add1=String.valueOf(rs.getInt("id"));
                String add2=rs.getString("first_name")+String.valueOf(rs.getInt("id"));
                String add3=rs.getString("dob");
                String result=add3.replace("/","");
                String add4=rs.getString("department");
                String sql="insert into users(division,username,password,id) values('"+add4+"','"+add2+"','"+result+"',"+add1+")";
             
                st=conn.createStatement();
                st.execute(sql);
                JOptionPane.showMessageDialog(null,"User account has been created successfully. "+"Username:"+add2+"  "+"Password:"+result);
              }
            }
             
            catch(Exception e)
            {
              e.printStackTrace();
            }
            finally {

                try{
                    rs.close();
                   

                }
               
                 catch(Exception e){
                     e.printStackTrace();
                 }
             
               
         }

     
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
     r_male.setSelected(true);
     r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
      r_female.setSelected(true);
      r_male.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     int x=JOptionPane.showConfirmDialog(this,"Are you sure to clear it??","Clear Record",JOptionPane.YES_NO_OPTION);
     if(x==0)
     {     
      clear();
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename=f.getAbsolutePath();
         ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
      try {
            
            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
            String sql="update staff_information set image=? where id=?";
            pst=conn.prepareStatement(sql);
            pst.setBytes(1,person_image);
            pst.setInt(2,Integer.parseInt(id));
            pst.executeUpdate();
    
        }
      catch(Exception e)
      {
         e.printStackTrace();
      }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Are you sure to delete record?","Delete Record",JOptionPane.YES_NO_OPTION);
     if(x==0)
     {   
        try {
                
                String sql = "delete from Staff_Information where id=?";
              
                pst=conn.prepareStatement(sql);
                pst.setInt(1,Integer.parseInt(id));
                
                if(Integer.parseInt(txt_id.getText())!=0)
                {
                pst.executeUpdate();
                clear();
                JOptionPane.showMessageDialog(this, "Record Deleted");
                }
                else
                 JOptionPane.showMessageDialog(this, "You cannot delete Root Account");  
                
           }
  catch(SQLException se){
         se.printStackTrace();
     
           }  
                catch(NumberFormatException e)
                {
                  e.printStackTrace();
                }
            catch (Exception e)

            {
                e.printStackTrace();
            }
        
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(Exception e){
                   e.printStackTrace();
                }
           }
        
        try {
                
                String sql = "delete from Users where id=?";
              
                pst=conn.prepareStatement(sql);
                pst.setInt(1,Integer.parseInt(id));
                
                pst.executeUpdate();
               
           }
            catch(Exception e)
            {
             e.printStackTrace();
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(Exception e){
                   e.printStackTrace();
                }
           }
          try {
                
                String sql = "delete from Allowance where id=?";
              
                pst=conn.prepareStatement(sql);
                pst.setInt(1,Integer.parseInt(id));
                
                pst.executeUpdate();
               
           }
            catch(Exception e)
            {
             e.printStackTrace();
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(Exception e){
                   e.printStackTrace();
                }
           }
           try {
                
                String sql = "delete from Deductions where emp_id=?";
              
                pst=conn.prepareStatement(sql);
                pst.setInt(1,Integer.parseInt(id));
                
                pst.executeUpdate();
               
           }
            catch(Exception e)
            {
             e.printStackTrace();
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(Exception e){
                   e.printStackTrace();
                }
           }
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        int x=JOptionPane.showConfirmDialog(this,"Are you sure to update record?","Update Record",JOptionPane.YES_NO_OPTION);
     if(x==0)
     {try
        {
       
         String sql="update staff_information set first_name=?,surname=?,"
                     +" Dob=?,Email=?,Telephone=?,Address=?,Department=?,"
                     + "Salary=?,Address2=?,Post_code=?, Designation=?,"
                   + "Status=?,job_title=?,Apartment=?,Date_hired=?,id=?,gender=? where id= ? ";
        pst=conn.prepareStatement(sql);
        pst.setString(1,txt_firstname.getText());
                pst.setString(2,txt_surname.getText());
                  java.util.Date dob=new java.util.Date();
                dob=txt_dob.getDate();
                java.util.Date doj=new java.util.Date();
                doj=txt_doj.getDate();
                java.sql.Date dob1=new java.sql.Date(dob.getTime());
                java.sql.Date doj1=new java.sql.Date(doj.getTime());
                DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
                String dob2=df.format(dob1);
                String doj2=df.format(doj1);
                pst.setString(3,dob2);
                pst.setString(4,txt_email.getText());
                pst.setString(5,txt_contact.getText());
                pst.setString(6,txt_address1.getText());
                pst.setString(7,txt_dept.getText());
                pst.setString(8,txt_salary.getText());     
                pst.setString(9,txt_address2.getText());
                pst.setString(10,txt_pc.getText());
                pst.setString(11,txt_desig.getText());
                pst.setString(12,txt_status.getText());
                pst.setString(13,txt_job.getText());
                pst.setString(14,txt_apt.getText());
                pst.setString(15, doj2);
                pst.setInt(16,Integer.parseInt(txt_id.getText()));
                 if(r_male.isSelected())
                    gender="m";
                else if(r_female.isSelected())
                    gender="f";
                pst.setString(17,gender);
                pst.setInt(18,Integer.parseInt(id));
                pst.execute();
        
        JOptionPane.showMessageDialog(null, "Record Updated");
        rs.close();
        }
         catch(NullPointerException ne)
        {
          ne.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
     }  
     try {
                
                 String sql="update Users set id=?,division=? where id= ? ";
              
                pst=conn.prepareStatement(sql);
                pst.setInt(1,Integer.parseInt( txt_id.getText()));
                pst.setString(2, txt_dept.getText());
                pst.setInt(3,Integer.parseInt(id));
                
                pst.executeUpdate();
               
           }
            catch(Exception e)
            {
             e.printStackTrace();
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(Exception e){
                   e.printStackTrace();
                }
           }
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try {
            jLabel19.setVisible(false);
            txt_id.setEnabled(true);
            clear();
            
            String sql = "select * from Staff_Information where id=?";

            pst=conn.prepareStatement(sql);
            
            pst.setInt(1,Integer.parseInt(txt_search.getText()));
            rs=pst.executeQuery();
            rs.next();
            String fs=rs.getString("first_name");
            txt_firstname.setText(fs);
            txt_surname.setText(rs.getString("surname"));
            String db=rs.getString("dob");            
            String dj=rs.getString("date_hired");
            DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
            Date dob=df.parse(db);
            Date doj=df.parse(dj);
            txt_dob.setDate(dob);
            txt_doj.setDate(doj);
            txt_contact.setText(rs.getString("telephone"));
            txt_email.setText(rs.getString("email"));            
            txt_address1.setText(rs.getString("address"));
            txt_address2.setText(rs.getString("address2"));
            if(rs.getString("gender").equals("m"))
            {
              r_female.setSelected(false);
              r_male.setSelected(true);
            }
            else
            {
                 r_male.setSelected(false);
              r_female.setSelected(true);
            }
            txt_salary.setText(rs.getString("salary"));
            txt_pc.setText(rs.getString("post_code"));
            txt_dept.setText(rs.getString("department"));
            txt_desig.setText(rs.getString("designation"));
            txt_status.setText(rs.getString("status"));
            txt_job.setText(rs.getString("job_title"));
            txt_apt.setText(rs.getString("apartment"));
            txt_id.setText(String.valueOf(rs.getString("id")));
            byte[] image=rs.getBytes("image");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
            img.setIcon(imageIcon);
        }
       
        catch(SQLException se){
            se.printStackTrace();

        }
       
        catch (Exception e)

        {
            e.printStackTrace();
        }

        finally {

            try{
                rs.close();
                pst.close();

            }
            catch(Exception e){
               e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        MainMenu o=new MainMenu();
        this.dispose();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_backMouseClicked

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
       id=txt_search.getText();
       txt_search.setText("");
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusGained
       jLabel19.setVisible(false);
    }//GEN-LAST:event_txt_idFocusGained

    private void txt_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusLost
         try
         {
               String sql1="select id from Staff_information";
         
                Statement statement=conn.createStatement();
                ResultSet rs1=statement.executeQuery(sql1);
                while(rs1.next())
                {
                   if(rs1.getInt("id")==Integer.parseInt(txt_id.getText()))
                   {
                       int j=JOptionPane.showConfirmDialog(this,"The id you have entered is already existing.Click YES to get one","ID exists",JOptionPane.YES_NO_OPTION);
                       if(j==0)
                         {
                                 idcount();
                          }
                      }
                }
         }
            catch(Exception e)
                    {
                     e.printStackTrace();
                    }
         
    }//GEN-LAST:event_txt_idFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_address1;
    private javax.swing.JTextField txt_address2;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_desig;
    private org.jdesktop.swingx.JXDatePicker txt_dob;
    private org.jdesktop.swingx.JXDatePicker txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
    
    private ImageIcon format= null;
    String filename=null;
    byte[] person_image=null;
    private String gender="";
    private String id=null;
    private int c=0;
    private int l=0;
}
