/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import employee.payroll.Emp;
import java.sql.SQLIntegrityConstraintViolationException;

/**
 *
 * @author dsajw
 */
public class Allowance extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Allowance
     */
    public Allowance() {
        initComponents();
        conn=db.getConnection();
        Update_table();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        lbl_emp.setText(Emp.username);
    }
   
    private void Update_table() {
    try{
        String sql ="select * from allowance";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        table_allowance.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    e.printStackTrace();
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ln = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dept = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_da = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_other = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_ot = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_bonus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_to = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_rph = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lbl_ta = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        txt_med = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_hra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_allowance = new javax.swing.JTable();
        lbl_pic = new javax.swing.JLabel();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/frame.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Search By Employee ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("EmployeeID:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        txt_empid.setEditable(false);
        txt_empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empidActionPerformed(evt);
            }
        });
        getContentPane().add(txt_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 131, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Firstname:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 125, -1, 30));

        txt_fn.setEditable(false);
        txt_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 131, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date Of Birth:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txt_dob.setEditable(false);
        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 131, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Lastname:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        txt_ln.setEditable(false);
        txt_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 131, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Department:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

        txt_dept.setEditable(false);
        txt_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 131, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Basic Salary(in ₹):");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 20));

        txt_salary.setEditable(false);
        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 131, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DA(in ₹):");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 20));

        txt_da.setText("0");
        txt_da.setInputVerifier(new numbers());
        txt_da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_daActionPerformed(evt);
            }
        });
        getContentPane().add(txt_da, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 131, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Other(in ₹):");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 20));

        txt_other.setText("0");
        txt_other.setInputVerifier(new numbers());
        txt_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otherActionPerformed(evt);
            }
        });
        getContentPane().add(txt_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 131, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Overtime(in hours):");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 120, 20));

        txt_ot.setText("0");
        txt_ot.setInputVerifier(new numbers());
        txt_ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ot, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 131, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Bonus(in ₹):");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 20));

        txt_bonus.setText("0");
        txt_bonus.setInputVerifier(new numbers());
        txt_bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bonusActionPerformed(evt);
            }
        });
        getContentPane().add(txt_bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 131, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Total Overtime(in hours):");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 150, 20));

        txt_to.setEditable(false);
        txt_to.setText("0");
        txt_to.setInputVerifier(new searchv());
        txt_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_toActionPerformed(evt);
            }
        });
        getContentPane().add(txt_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 131, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Rate per Hour:");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 20));

        txt_rph.setEditable(false);
        txt_rph.setText("0");
        txt_rph.setInputVerifier(new searchv());
        txt_rph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rphActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rph, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 131, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Save-icon.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Calculate.png"))); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/erase-128.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));

        txt_search.setInputVerifier(new searchv());
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 40, 370, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Total Amount(in ₹):");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, 20));

        lbl_ta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_ta.setText("0.00");
        getContentPane().add(lbl_ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 100, 20));

        label.setText("Logged in as:");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 83, 20));

        lbl_emp.setText("emp");
        getContentPane().add(lbl_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 130, 20));

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Right3Green.png"))); // NOI18N
        lbl_back.setText("Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 50, 40));

        txt_med.setText("0");
        txt_med.setInputVerifier(new numbers());
        txt_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_medActionPerformed(evt);
            }
        });
        getContentPane().add(txt_med, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 131, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Medical(in ₹):");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 20));

        txt_hra.setText("0");
        txt_hra.setInputVerifier(new numbers());
        txt_hra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 131, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("HRA(in ₹):");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 15));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 20));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        table_allowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_allowance.setAutoscrolls(false);
        jScrollPane1.setViewportView(table_allowance);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 850, 160));

        lbl_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/frame.jpg"))); // NOI18N
        lbl_pic.setPreferredSize(new java.awt.Dimension(901, 640));
        getContentPane().add(lbl_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empidActionPerformed

    private void txt_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void txt_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnActionPerformed

    private void txt_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void txt_daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_daActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_daActionPerformed

    private void txt_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otherActionPerformed

    private void txt_otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otActionPerformed

    private void txt_bonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bonusActionPerformed

    private void txt_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_toActionPerformed

    private void txt_rphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rphActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int salary = Integer.parseInt(txt_salary.getText());
        int overtime = Integer.parseInt(txt_ot.getText());

        double eight = 8;
        double days = 25;
        double dbop = 0;
        double overtimeRate = 1.5;
        
        //calculate the total hours of overtime
        double Total_Overtime = overtime * overtimeRate;
        String x = String.valueOf(Total_Overtime);
        txt_to.setText(x);

        //calculate overall overtime 
        dbop = salary /days/eight;
        String s = String.valueOf(dbop);
        txt_rph.setText(s);
        
        int med = Integer.parseInt(txt_med.getText());
        int da = Integer.parseInt(txt_da.getText());
        int hra = Integer.parseInt(txt_hra.getText());
        int bonus = Integer.parseInt(txt_bonus.getText());
        int other = Integer.parseInt(txt_other.getText());
        int f = med+bonus+other+da+hra;
        double calc = Total_Overtime * dbop+f;
        String c = String.valueOf(calc);
        lbl_ta.setText(c);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       txt_empid.setText("");
        txt_fn.setText("");
        txt_ln.setText("");
        txt_salary.setText("");
        txt_dob.setText("");
        txt_dept.setText("");
        txt_hra.setText("0");
        txt_med.setText("0");
        txt_da.setText("0");
        txt_bonus.setText("0");
        txt_other.setText("0");
        txt_rph.setText("0");
        txt_to.setText("0");
        txt_ot.setText("0");
        lbl_ta.setText("0.00");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{

            String sql ="select * from Staff_information where id=? ";

            pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(txt_search.getText()));
            rs=pst.executeQuery();
            rs.next();
                String add1 =String.valueOf(rs.getInt("id"));
                txt_empid.setText(add1);

                String add2 =rs.getString("first_name");
                txt_fn.setText(add2);

                String add3 =rs.getString("surname");
                txt_ln.setText(add3);

                String add4 =rs.getString("Dob");
                txt_dob.setText(add4);
                
                String add5 =rs.getString("Salary");
                txt_salary.setText(add5);

                String add6 =rs.getString("Department");
                txt_dept.setText(add6);

               
            
            
            
            

        }catch(Exception e){
            e.printStackTrace();
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        if (txt_empid.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Employee id Field is empty");
    } else if (txt_fn.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "First name Field is empty");
        
     } else if (txt_ln.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Surname name Field is empty");
        
    }
     else if (txt_dob.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Date of Birth name Field is empty");
        
    }
      else if (txt_salary.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Salary Field is empty");
        
    }
       else if (txt_dept.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Department Field is empty");
        
    }
      
    else {
        
        
        
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to save record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
        try {
            
            int value = Integer.parseInt(txt_empid.getText());
            String value1 =  txt_salary.getText();
            String value2 =  txt_bonus.getText();
            String value3 =  txt_med.getText();
            String value4 =  txt_other.getText();
            String value5 =  txt_rph.getText();
            String value6 =  txt_ot.getText();
            String value7 =  lbl_ta.getText();  
            String value8 =  txt_empid.getText();
            String value9 =  txt_fn.getText();
            String value10 = txt_ln.getText();
            String value11 =  txt_da.getText();
            String value12 =  txt_hra.getText();
           String sql= "insert into Allowance (created_by,id,overtime,medical,bonus,other,salary,rate,total_allowance,firstname,surname,da,hra) values ('"+value8+"',"+value+",'"+value6+"','"+value3+"','"+value2+"','"+value4+"','"+value1+"','"+value5+"','"+value7+"','"+value9+"','"+value10+"','"+value11+"','"+value12+"')";
             Statement st=null;    
            st=conn.createStatement();
            
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Allowance Added");
           
                  
        } 
         catch(SQLIntegrityConstraintViolationException e1)
        {
            int z= JOptionPane.showConfirmDialog(this,"Do you want to update the existing Allowance","Allowance exists",JOptionPane.YES_NO_OPTION);
            if(z==0)
            {
            try
               {
                    int value = Integer.parseInt(txt_empid.getText());
                String value1 =  txt_salary.getText();
                String value2 =  txt_bonus.getText();
                String value3 =  txt_med.getText();
                String value4 =  txt_other.getText();
                String value5 =  txt_rph.getText();
                String value6 =  txt_ot.getText();
                String value7 =  lbl_ta.getText();  
                String value8 =  txt_empid.getText();
                String value9 =  txt_fn.getText();
                String value10 = txt_ln.getText();
                String value11 =  txt_da.getText();
                 String value12 =  txt_hra.getText();
                String sql="update Allowance set created_by= '"+value8+"',id= "+value+",overtime= '"+value6+"',medical= '"+value3+"',bonus= '"+value2+"',other= '"+value4+"',salary= '"+value1+"',rate= '"+value5+"',total_allowance= '"+value7+"',firstname= '"+value9+"',surname = '"+value10+"',da = '"+value11+"',hra = '"+value12+"' where id= "+value+"";    
                Statement st=null;    
                st=conn.createStatement();
                st.execute(sql);
                JOptionPane.showMessageDialog(null, "Allowance Updated");
           }
          
           catch(Exception e)
           {
             e.printStackTrace();
           }
            }
            else
                e1.printStackTrace();
        }
        catch (Exception e)
            
        {
            e.printStackTrace();
        }
         try{
            Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String dateString = df.format(currentDate);

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            String timeString = sdf.format(d);

            String value0 = timeString;
            String values = dateString;
            int val = Emp.empId;
            
                String reg= "insert into Audit (emp_id, date, status) values ("+val+",'"+value0+" / "+values+"','Updated Record')";
                pst=conn.prepareStatement(reg);
                pst.execute();
            }
          catch (Exception e)

            {
                e.printStackTrace();
            }
        finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
        }
       }
         Update_table();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        MainMenu o=new MainMenu();
        this.dispose();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_backMouseClicked

    private void txt_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_medActionPerformed

    private void txt_hraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hraActionPerformed

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
      
    }//GEN-LAST:event_txt_searchFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Allowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_pic;
    private javax.swing.JLabel lbl_ta;
    private javax.swing.JTable table_allowance;
    private javax.swing.JTextField txt_bonus;
    private javax.swing.JTextField txt_da;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_hra;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JTextField txt_med;
    private javax.swing.JTextField txt_ot;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_rph;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_to;
    // End of variables declaration//GEN-END:variables
}
