/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;

/**
 *
 * @author dsajw
 */
public class login extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form login
     */
    public login() {
       // this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        conn=db.getConnection();
        currentDate();
        getCaptcha();
        
    }
    public String getCaptcha() {

    char data[] = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
            'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
            'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
            'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U',
            'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6',
            '7', '8', '9' };
    char index[] = new char[5];

    Random r = new Random();
    int i = 0;

    for (i = 0; i < (index.length); i++) {
        int ran = r.nextInt(data.length);
        index[i] = data[ran];
    }
    String s=new String(index);
    jLabel7.setText(s);
    return new String(index);
}

    
    
    public void currentDate()
    {
        /*
      Calendar cal=new GregorianCalendar();
      int month=cal.get(Calendar.MONTH);
      int day=cal.get(Calendar.DAY_OF_MONTH);
      int year=cal.get(Calendar.YEAR);
      lbl_date.setText(day+"/"+(month+1)+"/"+year);
      int hour=cal.get(Calendar.HOUR);
      int minute=cal.get(Calendar.MINUTE);
      int second=cal.get(Calendar.SECOND);
      lbl_time.setText(hour+":"+minute+":"+second);
     
      */
         datetime dt=new datetime();
        String d =dt.date("dd-MM-YYYY");
        lbl_date.setText(d);
        new javax.swing.Timer(0,new ActionListener(){
            public void actionPerformed(ActionEvent e) {
              datetime dt=new datetime();
              String d=dt.date("hh:mm:ss");
              lbl_time.setText(d);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(200, 170, 140, 30);

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        jPanel1.add(txt_password);
        txt_password.setBounds(200, 220, 140, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Others" }));
        txt_combo.setLightWeightPopupEnabled(false);
        jPanel1.add(txt_combo);
        txt_combo.setBounds(200, 300, 140, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 460, 110, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Select Division:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 300, 90, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 220, 80, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 170, 70, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Please enter your username and password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 370, 40);

        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(200, 260, 120, 23);

        jLabel6.setText("Captcha:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 360, 60, 40);

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel7.setText("jLabel6");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 360, 100, 40);

        jTextField1.setText("Type exactly as above");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(200, 410, 150, 30);

        jTextField2.setText("jTextField2");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(200, 220, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/update icon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 360, 20, 40);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 410, 130, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/login.JPG"))); // NOI18N
        jLabel5.setText("jkjkj");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 560);

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
        if(!jTextField1.getText().matches(jLabel7.getText()))
        {
          jLabel9.setText("Wrong Captcha");
          getCaptcha();
        }
        else if(jTextField1.getText().equals(jLabel7.getText()))
        {
                try
                {
                        String sql="select * from Users where (username=? and password=?)";
                        int count=0;
                        pst=conn.prepareStatement(sql);
                        pst.setString(1,txt_username.getText());
                        pst.setString(2,txt_password.getText());
                      //  pst.setString(3,txt_combo.getSelectedItem().toString());
                        rs=pst.executeQuery();
                       while(rs.next())
                       {

                                int id=rs.getInt(1);
                                System.out.println(id);
                                Emp.empId=id;
                                String username=rs.getString(2);
                                Emp.username=username;
                                count=count+1;
                                div=rs.getString("division");
                        }
                        String access=txt_combo.getSelectedItem().toString();

                        if(div.matches("Admin"))
                        {
                          if(count == 1)
                          {

                                    if(access.matches("Others"))
                                    {
                                            int x=JOptionPane.showConfirmDialog(this,"Would you like to enter as an Administrator?","Choose to Enter",JOptionPane.YES_NO_OPTION);
                                            if(x==0)
                                            {
                                                    MainMenu j=new MainMenu();
                                                    j.setVisible(true);
                                                    this.dispose();
                                                    Date currentDate = GregorianCalendar.getInstance().getTime();
                                                    DateFormat df = DateFormat.getDateInstance();
                                                    String dateString = df.format(currentDate);

                                                    Date d = new Date();
                                                    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                                                    String timeString = sdf.format(d);

                                                    String value0 = timeString;
                                                    String values = dateString;


                                                     int value = Emp.empId;
                                                     String reg = "insert into Audit (emp_id,date,status) values ("+value+",'"+value0+" / "+values+"','Logged In')";
                                                     pst=conn.prepareStatement(reg);
                                                     pst.execute();
                                                     this.dispose();
                                            }
                                            else
                                            {
                                                    Interface j=new Interface();
                                                    j.setVisible(true);
                                                    this.dispose();
                                            }
                                    }
                                    else
                                    {
                                            MainMenu j=new MainMenu();
                                            j.setVisible(true);
                                            this.dispose();
                                            Date currentDate = GregorianCalendar.getInstance().getTime();
                                            DateFormat df = DateFormat.getDateInstance();
                                            String dateString = df.format(currentDate);

                                            Date d = new Date();
                                            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                                            String timeString = sdf.format(d);

                                            String value0 = timeString;
                                            String values = dateString;


                                             int value = Emp.empId;
                                             String reg = "insert into Audit (emp_id,date,status) values ("+value+",'"+value0+" / "+values+"','Logged In')";
                                             pst=conn.prepareStatement(reg);
                                             pst.execute();
                                             this.dispose();
                                     }
                        }
                    else
                    {
                      JOptionPane.showMessageDialog(null,"Username or Password is wrong!");
                    }
        } 
          
        else if(!div.equals("Admin"))
        {

                    if(count==1)
                    {
                            if(access.equals("Admin"))
                            {
                                JOptionPane.showMessageDialog(this, "You are not allowed to enter as Administrator");
                            }
                            else
                            {
                                Interface j=new Interface();
                                j.setVisible(true);
                                this.dispose();
                            }
                    }
                    else
                    {
                           JOptionPane.showMessageDialog(null,"Username or Password you entered is wrong!");
                    }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Username or Password you entered is wrong!");
             
         e.printStackTrace();
        }
        finally
        {
           try{
             rs.close();
             pst.close();
           }        
           catch(Exception e){}
        }
      }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
    
        jTextField1.setText("");
          
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
       String s=txt_password.getText();
       jTextField2.setText(s);
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
        txt_password.setVisible(false);
        jTextField2.setVisible(true);
        }
        else
        {
        txt_password.setVisible(true);
        jTextField2.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        String s=jTextField2.getText();
       txt_password.setText(s);
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        getCaptcha();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JComboBox<String> txt_combo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    private String div=null;
}
